/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'date' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
  'timeSlot' : string,
}
export type AppointmentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface DashboardData {
  'appointments' : Array<Appointment>,
  'feedbacks' : Array<Feedback>,
}
export interface Feedback {
  'id' : bigint,
  'status' : FeedbackStatus,
  'review' : string,
  'name' : string,
  'createdAt' : bigint,
  'rating' : bigint,
}
export type FeedbackStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Admin-only: add a date to the blocked list.
   */
  'addBlockedDate' : ActorMethod<[string], undefined>,
  /**
   * / Admin-only: approve an appointment.
   */
  'approveAppointment' : ActorMethod<[bigint], undefined>,
  /**
   * / Admin-only: approve a feedback entry.
   */
  'approveFeedback' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Admin-only: view all appointments.
   */
  'getAllAppointments' : ActorMethod<[], Array<Appointment>>,
  /**
   * / Admin-only: view all feedback regardless of status.
   */
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  /**
   * / Public: only approved feedback is returned (no auth required).
   */
  'getApprovedFeedback' : ActorMethod<[], Array<Feedback>>,
  /**
   * / Public: get the list of blocked dates so the frontend can disable them.
   */
  'getBlockedDates' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Admin-only: get all appointments and all feedback in a single query.
   */
  'getDashboardData' : ActorMethod<[], DashboardData>,
  /**
   * / Admin-only: view all pending feedback.
   */
  'getPendingFeedback' : ActorMethod<[], Array<Feedback>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Admin-only: reject an appointment.
   */
  'rejectAppointment' : ActorMethod<[bigint], undefined>,
  /**
   * / Admin-only: reject a feedback entry.
   */
  'rejectFeedback' : ActorMethod<[bigint], undefined>,
  /**
   * / Admin-only: remove a date from the blocked list.
   */
  'removeBlockedDate' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Anyone (including guests) can book an appointment.
   */
  'submitAppointment' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  /**
   * / Anyone (including guests) can submit feedback.
   */
  'submitFeedback' : ActorMethod<[string, bigint, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];